version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - "5432:5432"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://$(cat /run/secrets/postgres_user):$(cat /run/secrets/postgres_password)@db/$(cat /run/secrets/postgres_db)
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app

secrets:
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt
  postgres_db:
    file: ./postgres_db.txt

volumes:
  db-data:

